call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
call pathogen#infect()

filetype plugin on
set ruler
set number
set nohlsearch
set backspace=2
set guioptions-=T " turn the menu bar off
set nocompatible

" ============================= Swap files ===================================

set noswapfile
set nobackup
set nowb

" ============================= Indentation ==================================

set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set expandtab
set smarttab

filetype indent on

" Don't set smart indent for python files
set smartindent
au! FileType python setl nosmartindent

" ============================= Colorscheme ==================================

syntax enable
set background=dark
colorscheme solarized

" ============================= Tag list =====================================

let Tlist_Auto_Open=1
let Tlist_Exit_OnlyWindow=1

" ============================= Powerline ====================================

set laststatus=2
set encoding=utf-8
let g:Powerline_symbols = 'fancy'
set t_Co=256

" ============================ Key bindings ==================================

imap jk <Esc>
imap kj <Esc>
vnoremap < <gv
vnoremap > >gv
nnoremap Y y$
cmap w!! %!sudo tee > /dev/null %

" ================================= LaTeX ====================================

" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
filetype plugin on

" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
set shellslash

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: This enables automatic indentation as you type.
"filetype indent on

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'
