call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

filetype on
set ruler
set ts=4
set sw=4
set autoindent
set smartindent
set number
set nohlsearch
set backspace=2
set guioptions-=T " turn the menu bar off
set noswapfile
set nocompatible
set foldmethod=indent

syntax on
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolor=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme desert

" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
filetype plugin on

" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
set shellslash

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: This enables automatic indentation as you type.
"filetype indent on

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'
