# Detect the current platform
platform='unknown'
unamestr=$(uname)
if [[ "$unamestr" == 'Linux' ]]; then
	platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
	platform='darwin'
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_LOCAL=$HOME/.zshrc-local

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="eastwood"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all
unsetopt auto_cd

function cfiles {
    find -regextype posix-egrep -regex '.*\.h$|.*\.hpp$|.*\.c$|.*\.cpp|.*\.cc$'
}

function cgrep {
    2>/dev/null grep -n "$@" $(cfiles) | nl | grep "$@"
}

export EDITOR=vim

export PATH=~/bin:$PATH

# Set up aliases
alias l='ls'
alias ll='ls -lh'
alias la='ls -a'
alias cs='cscope -R'
alias vi='vim'
alias ssh-r='ssh -R 17773:localhost:3128'
alias hd='hexdump -C'

# make colors work properly in tmux
alias tmux="TERM=screen-256color tmux"

if [[ "$platform" == 'darwin' ]]; then
	alias ls='ls -G'
elif [[ "$platform" == 'linux' ]]; then
	alias ls='ls --color=auto'
fi

if [[ -e "$ZSH_LOCAL" ]]; then
    source "$ZSH_LOCAL"
fi

echo -ne "\e]0; $(hostname) \007" 

#source ~/config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
